### ISSUE TITLE
Symbol question

### ISSUE THREAD

**Issue by sjaehn** [lvm/tidal-drum-patterns#1]
Hi Mauro, I just discovered your great collection of drum patterns. And I'm now busy with getting through the pattern definitions. But there is one thing I'm a bit confused. You used the symbol "mt" in many of your pattern (e. g., https://github.com/lvm/tidal-drum-patterns/blob/master/Sound/Tidal/Drum/Afro2a.hs ). Intuitively, I would associate it with a mid tom (GM code 47 or 48). But in https://github.com/lvm/tidal-midi-gm/blob/master/Sound/Tidal/MIDI/GMPerc.hs "mt" is assigned to mute triangle (GM code 80). What is the right one ?

**Comment by lvm** [comment]
hi @sjaehn sorry for the confussion. You're right `mt` is MIDI note 47. 
Just in case, from now on check the mapping here: https://github.com/tidalcycles/Tidal/blob/main/src/Sound/Tidal/Params.hs#L572

(Already sent a PR to Tidalcycles to fix this situation you mention as well)
