### ISSUE TITLE
patterns translated for strudel 

### ISSUE THREAD

**Issue by urswilke** [lvm/tidal-drum-patterns#6]
Not an issue, just a comment:

I translated your patterns to strudel. See the related discussion [here](https://github.com/tidalcycles/strudel/discussions/373).

Perhaps you can answer this question [there](https://github.com/tidalcycles/strudel/discussions/373#discussioncomment-4685511) where the `ch rm ac cy oh cow cl sh` samples come from:

> Maybe there is another set of samples I am not aware of?

Anyways, thanks for your repo!

**Comment by lvm** [comment]
Thanks for using it :-) 

I'll try to follow the thread over there and answer but for now I can tall you that I rarely used Dirt samples, most of the time used a set of my own or MIDI notes. I'd have to look for those though.
